translate invalid-hook-call-warning and invalid-aira-prop
reactjs/vi.reactjs.org pull request #200
Opened 2021-09-15 13:06 UTC by dinhtrung1308

2021-09-15 13:21 UTC, dinhtrung1308 commented
Anh review dùm em nhé. Cảm ơn anh !!!

2021-09-15 15:46 UTC, Ryan-LT commented
> Anh review dùm em nhé. Cảm ơn anh !!!

Sure em! Sáng mai nhé 😄

2021-09-16 03:30 UTC, Ryan-LT commented on content/warnings/invalid-aria-prop.md
> +The invalid-aria-prop warning sẽ xuất hiện nếu bạn cố gắng xuất một DOM element với một aria-* prop cái mà không tồn tại trong Web Accessibility Initiative (WAI) Accessible Rich Internet Application
cố gắng xuất
-> Giữ nguyên từ render nhé e

2021-09-16 03:41 UTC, Ryan-LT requested changes
Em check lại giúp anh nhé. Cảm ơn em

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-aria-prop.md
> +The invalid-aria-prop warning sẽ xuất hiện nếu bạn cố gắng xuất một DOM element với một aria-* prop cái mà không tồn tại trong Web Accessibility Initiative (WAI) Accessible Rich Internet Application
cái mà không tồn tại
-> Chỗ này hơi lấn cấn nè

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-aria-prop.md
> +1. Nếu bạn thấy bạn đang sử dụng đúng prop, kiểm tra chính tả một cách kỹ càng. `aria-labelledby` và `aria-activedescendant` thường được đánh vần sai.
Em rephrase lại đoạn này nhé!

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-aria-prop.md
> +2. React không nhận ra thuộc tính bạn mô tả. Vấn đề này có vẻ sẽ được sửa trong phiên bản tương lai của React. Tuy nhiên, React hiện tại loại bỏ tất cả thuộc tính không nhận diện được, vì thế mô tả c
xuất ra.
-> Giữ nguyên từ render nhé em

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> + Bạn có thể ở đây bởi vì bạn nhận được nhũng thông báo lỗi dưới đây:
Bạn có thể ở đây bởi vì bạn nhận được nhũng thông báo lỗi dưới đây:
->  Bạn có thể ở đây bởi vì bạn gặp những thông báo lỗi dưới đây:
Spelling nha em

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> +Bạn có thể đang sử dụng phiên bản `react-dom` (< 16.8.0) hoặc `react-native` (< 0.59) những cái này chưa hỗ trợ Hooks. Bạn có thể chạy `npm ls react-dom` hoặc `npm ls react-native` trong thư mục ứng
những cái này
->những phiên bản này

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> +Bạn có thể đang sử dụng phiên bản `react-dom` (< 16.8.0) hoặc `react-native` (< 0.59) những cái này chưa hỗ trợ Hooks. Bạn có thể chạy `npm ls react-dom` hoặc `npm ls react-native` trong thư mục ứng
nhiều hơn ở dưới
-> Liệt kê bên dưới

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> +Bạn chỉ có thể gọi Hooks **trong khi React đang xuất một function component**:
đang xuất
-> Render

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> +* ✅ Gọi nó ở đầu phần thân của một function component.
phần thân
-> Bên trong

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> +* ✅ Gọi nó ở đầu phần thân của một [custom Hook](/docs/hooks-custom.html).
phần thân
-> Bên trong

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> +Để tránh nhầm kẫn , Nó **không** được hỗ trợ để gọi Hooks trong những trường hợp:
nhầm kẫn
-> Spelling em nhe

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> +* 🔴 Đừng gọi Hooks bên trong các hàm được dùng trong `useMemo`, `useReducer`, hoặc `useEffect`.
các hàm
-> Giữ nguyên function có vẻ dễ hiểu hơn nè

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> +Nếu bạn vi phạm những quy tắc này, bạn có thể thấy lỗi này.
Nếu bạn vi phạm những quy tắc này
-> Nếu bạn vi phạm những quy tắc trên

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> +>[Custom Hooks](/docs/hooks-custom.html) *có thể* gọi những Hooks khác (hoàn toàn do mục đích của nó). Điều này hoàn toàn hữu hiệu bởi vì custom Hooks được hỗ trợ chỉ để được gọi khi một function com
đang xuất
-> Đang render

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> +Để cho Hooks hoạt động,  `react` được thêm từ mã ứng dụng cần được giải quyết giống như `react` được thêm từ gói `react-dom`.
cho Hooks hoạt động,
-> Hooks hoạt động,

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> +Nếu những `react` được nhập này giải quyết hai đôi tượng xuất khác nhau, bạn sẽ thấy cảnh báo. Điều có thể xảy ra nếu bạn **đột ngột kết thúc với hai phiên bản** của gói `react`.
được nhập
-> Được import

2021-09-16 03:41 UTC, Ryan-LT commented on content/warnings/invalid-hook-call-warning.md
> +Nếu bạn sử dụng Node để quản lý gói, bạn có thể kiểm tra nó bằng cách chạy câu lệnh này trong thư mục dự án của bạn:
quản lý gói
-> Giữ nguyên package nhé

2021-09-16 04:39 UTC, dinhtrung1308 commented
Dạ em cảm ơn ạ. Để em sửa lại.

2021-09-16 05:21 UTC, dinhtrung1308 commented
Dạ em đang sửa lỗi theo yêu cầu ạ.

2021-09-16 05:31 UTC, Ryan-LT approved these changes

2021-09-16 05:31 UTC, merged