feat: translate addons test utils (WIP)
reactjs/vi.reactjs.org pull request #211
Opened 2021-09-16 04:29 UTC by danglequocbao001

chore: pull code

2021-09-18 02:43 UTC, Ryan-LT commented
Hi @danglequocbao001, Em giúp anh check lại một lần nữa nhé, Anh đọc thấy hơi khó hiểu. Em đừng dịch thô từ Eng sang Viet. Em đọc hiểu rồi dịch ấy, sẽ giúp các bạn mới dễ tiếp cận hơn nè.

Cảm ơn em nhé!

2021-09-18 02:45 UTC, Ryan-LT requested changes
Hi @danglequocbao001, Em giúp anh check lại một lần nữa nhé, Anh đọc thấy hơi khó hiểu. Em đừng dịch thô từ Eng sang Viet. Em đọc hiểu rồi dịch ấy, sẽ giúp các bạn mới dễ tiếp cận hơn nè.

Cảm ơn em nhé!

2021-09-18 03:09 UTC, danglequocbao001 commented
> Hi @danglequocbao001, Em giúp anh check lại một lần nữa nhé, Anh đọc thấy hơi khó hiểu. Em đừng dịch thô từ Eng sang Viet. Em đọc hiểu rồi dịch ấy, sẽ giúp các bạn mới dễ tiếp cận hơn nè.
> 
> Cảm ơn em nhé!

Okay a ơi.

2021-09-18 03:13 UTC, danglequocbao001 commented
@Ryan-LT a có thể chỉ giúp e những chỗ cần xem lại không, vì e dịch sát theo cách e hiểu nhất rồi á, những thuật ngữ chuyên ngành e vẫn giữ nguyên.

2021-09-18 12:33 UTC, Ryan-LT commented
> @Ryan-LT a có thể chỉ giúp e những chỗ cần xem lại không, vì e dịch sát theo cách e hiểu nhất rồi á, những thuật ngữ chuyên ngành e vẫn giữ nguyên.

Hi em, Đại ý là em đừng dịch từng từ sang Tiếng Việt mà hãy đọc hiểu rồi em dịch cả đoạn bằng ngôn ngữ tự nhiên. Khá nhiều nên nếu anh chỉ từng chỗ thì sẽ mất nhiều thời gian lắm nè.

2021-09-18 12:38 UTC, Ryan-LT commented
**Ví dụ như đoạn đầu này:**

> `ReactTestUtils` makes it easy to test React components in the testing framework of your choice. At Facebook we use [Jest](https://facebook.github.io/jest/) for painless JavaScript testing. Learn how to get started with Jest through the Jest website's [React Tutorial](https://jestjs.io/docs/tutorial-react).

`ReactTestUtils` khiến việc test React component trở nên dễ dàng hơn khi bạn dùng testing framework nào đó mà bạn thích. Ở Facebook, chúng tôi dùng [Jest](https://facebook.github.io/jest/) để test JavaScript một cách dễ dàng hơn. Các bạn có thể tìm hiểu thêm về Jest qua website này [Hướng Dẫn Test React](https://jestjs.io/docs/tutorial-react).

2021-09-18 12:39 UTC, Ryan-LT commented
Em thấy thế nào? Nếu được em cố gắng dịch theo ngôn ngữ tự nhiên như vậy nhé, hơi mất thời gian chút nhưng mình sẽ học được rất nhiều đó.

Cảm ơn em nhiều!

2021-09-20 02:42 UTC, Ryan-LT requested changes
Hi em, Sorry cuối tuần anh bận chút việc nên ko review được.

Em giúp anh check lại nhé? Cố gắng dịch theo ngôn ngữ tự nhiên, đừng dịch thẳng từ Eng sang Viet nhé.

Anh cảm ơn em!

2021-09-20 11:17 UTC, danglequocbao001 commented
> Hi em, Sorry cuối tuần anh bận chút việc nên ko review được.
> 
> Em giúp anh check lại nhé? Cố gắng dịch theo ngôn ngữ tự nhiên, đừng dịch thẳng từ Eng sang Viet nhé.
> 
> Anh cảm ơn em!

Okay a ơi, cho e thư thả làm trong vài ngày nha, dạo này e bị việc quật dữ quá :v thank kiu a

2021-09-21 01:35 UTC, danglequocbao001 commented
> Hi em, Sorry cuối tuần anh bận chút việc nên ko review được.
> 
> Em giúp anh check lại nhé? Cố gắng dịch theo ngôn ngữ tự nhiên, đừng dịch thẳng từ Eng sang Viet nhé.
> 
> Anh cảm ơn em!

E mới fix lại rồi á, a review giúp e nha.

2021-09-21 06:41 UTC, Ryan-LT approved these changes
Nice! 👍

2021-09-21 06:41 UTC, merged