Translate: integrating-with-other-libraries page
reactjs/vi.reactjs.org pull request #222
Opened 2021-09-17 15:11 UTC by ncnthien

Translate the integrating-with-other-libraries page in the advanced guides section of the documentation.

2021-09-18 03:05 UTC, Ryan-LT requested changes
Em cố gắng dịch theo ngôn ngữ tự nhiên chút nhé, anh sợ mấy bạn mới đọc sẽ khó hiểu đấy

2021-09-18 04:45 UTC, ncnthien commented
> Em cố gắng dịch theo ngôn ngữ tự nhiên chút nhé, anh sợ mấy bạn mới đọc sẽ khó hiểu đấy

Anh góp ý giúp em một vài chỗ được không ạ, tại vì đây là lần đầu em dịch cũng như contribute cho một dự án cộng đồng như thế này nên chưa có nhiều kinh nghiệm, mong anh giúp đỡ ạ ^^

2021-09-18 07:20 UTC, ncnthien commented
Em vừa mới dịch lại theo cách thoáng ra hơn một chút, anh rảnh thì xem lại giúp em rồi cho em ý kiến a

2021-09-18 13:02 UTC, Ryan-LT requested changes

2021-09-20 02:43 UTC, Ryan-LT approved these changes
Great effort! 🍰

2021-09-20 02:43 UTC, merged